<a href="https://colab.research.google.com/github/JeevanJayakumar/Jeevan_24-14-13/blob/main/Assn2_Jeevan_Jayakumar_24_14_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment 2

Name: Jeevan Jayakumar

Reg No: 24-14-13

Programme: M.Tech Modelling & Simulation

In [58]:
import numpy as np
import numpy.random as npr

Question 1

In [102]:
# 1.a

print("Q1. a\n")
var1=np.arange(1,31)
print("var1:",var1)
print("shape=",var1.shape)

Q1. a

var1: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
shape= (30,)


In [103]:
# 1.b

print("Q1. b\n")
var2=var1.reshape(10,3)
print("var2:",var2)
print("shape=",var2.shape)

Q1. b

var2: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]]
shape= (10, 3)


In [104]:
# 1.c

print("Q1. c\n")
var3=var1.reshape(5,3,2)
print("var3:",var3)
print("shape=",var3.shape)

Q1. c

var3: [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]

 [[25 26]
  [27 28]
  [29 30]]]
shape= (5, 3, 2)


In [105]:
# 1.d

print("Q1. d\n")
var2[1,0]= -1
print("var2:\n",var2, "\n var1:\n",var1, "\n var3:\n",var3)


print("\nYes,the values in var3 also changed. \nReshape returns a view of the original array, not a copy.")

Q1. d

var2:
 [[ 1  2  3]
 [-1  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]] 
 var1:
 [ 1  2  3 -1  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30] 
 var3:
 [[[ 1  2]
  [ 3 -1]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]

 [[25 26]
  [27 28]
  [29 30]]]

Yes,the values in var3 also changed. 
Reshape returns a view of the original array, not a copy.


In [106]:
# 1.e

print("Q1. e\n")
sum1=np.sum(var3,axis=1)
print("sum1:\n",sum1)

sum2=np.sum(var3,axis=2)
print("sum2:\n",sum2)

sum3=np.sum(var3,axis=(0,2))
print("sum3:\n",sum3)

Q1. e

sum1:
 [[ 9  7]
 [27 30]
 [45 48]
 [63 66]
 [81 84]]
sum2:
 [[ 3  2 11]
 [15 19 23]
 [27 31 35]
 [39 43 47]
 [51 55 59]]
sum3:
 [135 150 175]


In [107]:
# 1.f

print("Q1. f\n")
print("var2 second row: ",var2[1])
print("var2 last column: ",var2[:,-1])
print("var2 sub matrix:\n",var2[:2,1:])

Q1. f

var2 second row:  [-1  5  6]
var2 last column:  [ 3  6  9 12 15 18 21 24 27 30]
var2 sub matrix:
 [[2 3]
 [5 6]]


Question 2

In [108]:
# 2.a

print("Q2. a\n")
vector1=np.arange(10)
vector1=vector1+1
print(vector1)

Q2. a

[ 1  2  3  4  5  6  7  8  9 10]


In [109]:
# 2.b

print("Q2. b\n")
A=vector1.reshape(10,1)+ vector1
print(A)

Q2. b

[[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


In [110]:
# 2.c

print("Q2. c\n")
data = np.exp(npr.randn(50,5))
print("data:\n",data,"\nshape:",data.shape)

Q2. c

data:
 [[ 1.45872846  0.42984675  0.54870967  1.90782459  0.5170894 ]
 [ 0.62891035  0.60949598  0.46801776  0.03436241  1.35294646]
 [ 7.36782686  4.02315263  3.93180685  0.752586    2.38876862]
 [ 1.79357897  1.34469621  0.56751154  1.37574345  2.20387201]
 [ 2.21823319  1.46437335  1.45713453  2.42202107  1.20572816]
 [ 2.52133373  0.62499063  0.17949526  0.5544297   4.33432364]
 [ 0.40340837  0.43044262  0.25275661  0.36451491  2.29172857]
 [ 2.0574004   0.82226231  3.39700895  0.45162881  1.92220862]
 [ 1.00532073  1.09301601  2.51757043  1.5881438   0.38172652]
 [ 1.88358599  1.26117613  0.10063896  0.83967145  0.84407268]
 [ 1.15350909  2.23168822  0.36522098  1.00152946  3.12377386]
 [ 0.25229619  1.11642703  0.44600676  0.21643448  1.80363493]
 [ 2.43184756  0.07502093  0.59164013  1.82148224  1.18390412]
 [ 1.06427074  1.79833188  0.59281252  1.83294959  0.42012525]
 [ 0.64390591  0.87073808  0.69795832  1.2751196   0.36439393]
 [ 0.16416103  0.11679262  0.76320393  1.

In [111]:
# 2.e

print("Q2. e\n")
mean=np.mean(data,axis=0)
std=np.std(data,axis=0)
print("Mean: ",mean)
print("Standard deviation: ",std)

Q2. e

Mean:  [1.57277496 1.79463993 1.21679577 1.62760561 1.40925502]
Standard deviation:  [1.52490779 2.39876404 1.06376714 1.54282083 1.11208936]


In [112]:
# 2.f
print("Q2. f\n")
normalized=(data-mean)/std
print("Normalized mean: ",np.mean(normalized,axis=0))
print("Normalaized std deviation: ",np.std(normalized,axis=0))


Q2. f

Normalized mean:  [ 1.33226763e-17 -3.84137167e-16  8.88178420e-17  3.99680289e-17
 -7.10542736e-17]
Normalaized std deviation:  [1. 1. 1. 1. 1.]


Question 3


In [113]:

def vandermonde (N):
  vec=np.arange(N)+1
  power=np.arange(N)
  power=np.matrix(power).T
  vander=vec**power
  return vander.T


In [114]:
# 3.a

vander=vandermonde(12)
print(vander)

[[           1            1            1            1            1
             1            1            1            1            1
             1            1]
 [           1            2            4            8           16
            32           64          128          256          512
          1024         2048]
 [           1            3            9           27           81
           243          729         2187         6561        19683
         59049       177147]
 [           1            4           16           64          256
          1024         4096        16384        65536       262144
       1048576      4194304]
 [           1            5           25          125          625
          3125        15625        78125       390625      1953125
       9765625     48828125]
 [           1            6           36          216         1296
          7776        46656       279936      1679616     10077696
      60466176    362797056]
 [           1        

In [115]:
# 3.b

vander=vander.T
x=np.ones(12)
x=x.T
b=np.matmul(vander,x)
print("b = ",b)

b =  [[1.20000000e+01 7.80000000e+01 6.50000000e+02 6.08400000e+03
  6.07100000e+04 6.30708000e+05 6.73595000e+06 7.33994040e+07
  8.12071910e+08 9.09203303e+09 1.02769131e+11 1.17068436e+12]]


In [116]:
# 3.c
xn=np.linalg.inv(vander)
b=b.T
result=np.matmul(xn,b)
print("result: ",result.T)

result:  [[1.40164465 0.59611278 1.00202715 1.00117254 0.9974848  1.00318933
  0.99717116 1.00180864 0.99918208 1.00024882 0.99995425 1.00000385]]


In [117]:
# 3.d
res2=np.linalg.solve(vander,b)
print("result: ",res2.T)

result:  [[0.99997509 1.00022004 0.99910211 1.0022556  0.99613289 1.00472989
  0.99580438 1.00269135 0.99877921 1.00037229 0.99993139 1.00000578]]


https://github.com/JeevanJayakumar/Jeevan_24-14-13/blob/main/Assn2_Jeevan_Jayakumar_24_14_13.ipynb
